### ISSUE TITLE
dist directory should be untracked

### ISSUE THREAD

**Issue by eltronix** [codingedward/ailing-planet#1]
Hey Ed, its Elton. 
You should probably remove the dist directory from version control.
Kudos, this is such good work btw.

**Comment by codingedward** [comment]
Thanks Elton! This is much appreciated :tada:

About the `/dist` directory, I agree we shouldn't have it on version control. It came as a result of using GitHub pages to deploy the app and so I'm currently pushing the `/dist` subtree to the `gh-pages` branch (that is using `git subtree push --prefix dist origin gh-pages`). 

I'm not sure there would be a way to have a branch-specific `.gitignore` file so that the `/dist` isn't ignored on the `gh-pages` but is ignored on `master`. 

I'd appreciate any suggestions 👍

**Comment by codingedward** [comment]
I found a neat way to generate the dist folder on a temporary branch and to push that to `gh-pages` therefore we are able to not track `/dist`
