### ISSUE TITLE
Country names on the left hard to read once I click play for the first time

### ISSUE THREAD

**Issue by jmnyarega** [codingedward/ailing-planet#5]
The names on the left can be hard to read and it kinda becomes a guessing game to figure out what country is going to be displayed. Maybe display the top three only?

**Comment by codingedward** [comment]
I think we kind of solved this problem by reducing the aspect ratio of the chart data race. Initially, one could only read country names of the top three bars of the chart but now it is showing for almost all countries (provided it doesn't have more than say, 8 characters in its name 😅 ). 

I also included a feature to be able to click on the bars (so that if the country name is not entirely visible and the user clicked on the bar, the bar's country gets focused on).

Maybe moving the names of the countries to the right of the bar, so that they are outside of the bar may help. I couldn't find a consistent way to do this though while preserving the length of the bar.
