### ISSUE TITLE
The app doesn't render well on large screens or small screens 

### ISSUE THREAD

**Issue by jmnyarega** [codingedward/ailing-planet#6]

**Comment by codingedward** [comment]
I think for large screens, we only have to remove the maximum width constraint of the chart data race. Maybe we could ensure it at least always 25% of the screen.

For the tiny screens, I'm up for suggestions. When building it I tried to make it as responsive as possible and to reduce the computation required (since they are likely mobile phones). For instance, if it is loaded on a mobile phone, the bars on the chart are reduced to just 5 instead of the ten. I'm up for more ways we can improve it :+1:
